# Generated by Django 3.0.2 on 2020-02-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='नाम (अनिवार्य)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='इमेल (अनिवार्य)')),
                ('subject', models.EmailField(max_length=254, unique=True, verbose_name='विषय (अनिवार्य)')),
                ('message', models.TextField(blank=True, null=True, verbose_name='प्रतिक्रिया दिनुहोस्')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
