# Generated by Django 3.0.2 on 2020-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20200218_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='name',
            field=models.CharField(default='main', max_length=200),
        ),
    ]
