# Generated by Django 3.0.2 on 2020-02-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0004_auto_20200210_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
