# Generated by Django 3.0.2 on 2020-05-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='newspost.Tag'),
        ),
    ]
